name: deploy-auth

on: 
  push:
    branches:
      - master
    paths:
      - 'auth/**'
      
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd auth && docker build -t deekhalden/auth .
      - run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      - run: docker push deekhalden/auth
      - run: |
              curl -fsSL https://clis.cloud.ibm.com/install/linux | sh 
              ibmcloud --version
      - run: |
              ibmcloud login -u $IBM_USERNAME -p $IBM_PASSWORD
              ibmcloud ks cluster config -c c5e3kbcf0tqkg387jgdg
              kubectl config current-context
              kubectl rollout restart deployment auth-depl
        env:
          IBM_USERNAME: ${{ secrets.IBM_USERNAME }}
          IBM_PASSWORD: ${{ secrets.IBM_PASSWORD }}
              
        
        
        
