name: deploy-auth

on:
  push:
    branches:
      - master
    paths:
      - 'auth/**'
      
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd auth && docker build -t deekhalden/auth .
      - run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      - run: docker push deekhalden/auth
      - run: |
              curl -fsSL https://clis.cloud.ibm.com/install/linux | sh
              ibmcloud --version
      - run: ibmcloud login -u $IBM_USERNAME -p $IBM_PASSWORD -g default
        env:
          IBM_USERNAME: ${{ secrets.IBM_USERNAME }}
          IBM_PASSWORD: ${{ secrets.IBM_PASSWORD }}
      - run: ibmcloud cr region-set "eu-de"
      - run: ibmcloud cr login
      - run: ibmcloud ks cluster config -c c5e3kbcf0tqkg387jgdg
      - run: kubectl config current-context
      - run: kubectl rollout restart deployment auth-depl
