name: deploy-manifests

on:
  push:
    branches:
      - master
    paths:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2\
      - uses: digitalocean/action-doctl@V2
      - run: kubectl apply -f infra/k8s
      - run: kubectl apply -f infra/k8s-prod
