name: deploy-manifests

on:
  push:
    branches:
      - master
    paths:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      
      - run: sudo kubectl apply -f infra/k8s
      - run: sudo kubectl apply -f infra/k8s-prod
